const ShopActionTypes = {
    SET_CURRENT_COLLECTIONS: 'SET_CURRENT_COLLECTIONS',
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILED: 'FETCH_COLLECTIONS_FAILED'

}
export default ShopActionTypes;